name: Infra test-pre-deploy

on:
    push:
        branches:
            - main
            - feature*
    pull_request:
        branches:
            - feature*
env:
  AWS_REGION: "ap-south-1"
  ENVIRONMENT: "development"

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read   # This is required for actions/checkout

jobs: 
    terraform-init:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.10.5
            
            - name: configure aws auth
              uses: aws-actions/configure-aws-credentials@v4.0.3
              with:
                role-to-assume: arn:aws:iam::288761748973:role/github_oidc_role-dev
                role-session-name: GitHub_to_AWS_via_FederatedOIDC
                aws-region: ${{ env.AWS_REGION }}

            - name: Initialize Terraform
              env:
                environment: development
              run: |
                ls -R $GITHUB_WORKSPACE
                cd $GITHUB_WORKSPACE/infrastructure/lambda
                echo -e "\033[0;32mRunning terraform init in: $(basename $(pwd))\033[0m"
                ./ter.sh init ${{env.environment}}
                cd $GITHUB_WORKSPACE/infrastructure/s3
                echo -e "\033[0;32mRunning terraform init in: $(basename $(pwd))\033[0m"
                ./ter.sh init ${{env.environment}}
