name: Slack Notification

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      message:
        required: false
        type: string

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notify build start
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: |
              :hourglass_flowing_sand: GitHub Action build starts: In Progress
              Repository: *${{ github.repository }}*
              Commit: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>
              Author: ${{ github.event.head_commit.author.name }}
              Branch: <https://github.com/${{ github.repository }}/tree/${{ github.ref }}|${{ github.ref }}>
              URL: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
                  
      - name: Run some commands
        run: |
          echo "Hello, world!"
          echo "The time is $(date)."
          seep 30

      - name: Notify build success
        if: success()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: |
              :tada: *GitHub Action build succeeded* :tada:
              Repository: *${{ github.repository }}*
              Commit: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>
              Author: ${{ github.event.head_commit.author.name }}
              Branch: <https://github.com/${{ github.repository }}/tree/${{ github.ref }}|${{ github.ref }}>
              URL: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}

      - name: Notify build failure
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: |
              :x: *GitHub Action build failed* :x:
              Repository: *<${{ github.repository }}>* 
              Commit: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>
              Author: ${{ github.event.head_commit.author.name }}
              Branch: <https://github.com/${{ github.repository }}/tree/${{ github.ref }}|${{ github.ref }}>
              URL: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
