name: Slack Notification

on:
  push:
    branches:
      - set-*

# env:
#   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Greet the reader
        uses: slackapi/slack-github-action@v2.0.0
        with:
            webhook: "https://hooks.slack.com/services/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"
            webhook-type: incoming-webhook
            payload: |
                text: "Greetings!"
        env:
            SLACK_CHANNEL_ID: "#github-actions-workflows"

     