name: Slack Notification

on:
    push:
        branches:
            - set-*
    # pull_request:
    #     branches:
    #         - main

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Notify Slack on success
              if: success()
              uses: slackapi/slack-github-action@v1.23.0
              with:
                payload: |
                    {
                        "channel": "#github-actions-workflows",
                        "attachments": [
                            {
                                "color": "good",
                                "title": "Job Succeeded",
                                "fields": [
                                    {
                                        "title": "Repository",
                                        "value": "${{ github.repository }}",
                                        "short": true
                                    },
                                    {
                                        "title": "Commit",
                                        "value": "${{ github.sha }}",
                                        "short": true
                                    },
                                    {
                                        "title": "Author",
                                        "value": "${{ github.actor }}",
                                        "short": true
                                    },
                                    {
                                        "title": "Event Name",
                                        "value": "${{ github.event_name }}",
                                        "short": true
                                    }
                                ]
                            }
                        ]
                    }
                env:
                    SLACK_BOT_TOKEN: "https://hooks.slack.com/services/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"

            - name: Notify Slack on failure
              if: failure()
              uses: slackapi/slack-github-action@v1.23.0
              with:
                payload: |
                    {
                        "channel": "#your-channel",
                        "attachments": [
                            {
                                "color": "danger",
                                "title": "Job Failed",
                                "fields": [
                                    {
                                        "title": "Repository",
                                        "value": "${{ github.repository }}",
                                        "short": true
                                    },
                                    {
                                        "title": "Commit",
                                        "value": "${{ github.sha }}",
                                        "short": true
                                    },
                                    {
                                        "title": "Author",
                                        "value": "${{ github.actor }}",
                                        "short": true
                                    },
                                    {
                                        "title": "Event Name",
                                        "value": "${{ github.event_name }}",
                                        "short": true
                                    }
                                ]
                            }
                        ]
                    }
                env:
                    SLACK_BOT_TOKEN: "https://hooks.slack.com/services/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"


                    