name: Slack Notification

on:
  push:
    branches:
      - set-*

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Greet the reader
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "GitHub Action build starts: In Progress\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  
      - name: run some commands
        run: |
          echo "Hello, world!"
          echo "The time is $(date)."
          sleep 30
      - name: Notify Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            if fails
              text: "GitHub Action build failed\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            else
              text: "GitHub Action build succeeded\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"

        