name: terraform build and deployment

on: 
  push:
    branches:
      - main
      - set-*
  pull_request:

env:
  AWS_REGION: "us-east-1"
  GITHUB_ROLE_ARN: "arn:aws:iam::342914800082:role/github_oidc_role_expensive-tracker"

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read   # This is required for actions/checkout

jobs:      
    sam-build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: Set up Python
          uses: actions/setup-python@v4

        - name: Notify build start
          uses: slackapi/slack-github-action@v2.0.0
          with:
            webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
            webhook-type: incoming-webhook
            payload: |
              text: |
                :hourglass_flowing_sand: GitHub Action build starts: In Progress
                Repository: *${{ github.repository }}*
                Commit: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>
                Author: ${{ github.event.head_commit.author.name }}
                Branch: <https://github.com/${{ github.repository }}/tree/${{ github.ref }}|${{ github.ref }}>
                URL: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}

       
        - name: setup sam
          uses: aws-actions/setup-sam@v2
        - run: |
            # ls -R
            cd $GITHUB_WORKSPACE/sam-app-init
            # ls -al
            sam build --use-container
        - name: store the build cache
          uses: actions/cache@v3
          with:
            path: ${{ github.workspace }}/sam-app-init/.aws-sam
            key: sam-cache-${{ github.sha }}

    sam-invoke:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
        - name: setup sam
          uses: aws-actions/setup-sam@v2
        - name: Restore .aws-sam cache
          uses: actions/cache@v3
          with:
            path: ${{ github.workspace }}/sam-app-init/.aws-sam
            key: sam-cache-${{ github.sha }}
            restore-keys: |
              sam-cache-
        - run: |
            # ls -R
            cd $GITHUB_WORKSPACE/sam-app-init
            ls -R
            sam local invoke

        - name: Notify build failure
          if: failure()
          uses: slackapi/slack-github-action@v2.0.0
          with:
            webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
            webhook-type: incoming-webhook
            payload: |
              text: |
                :x: *GitHub Action build failed* :x:
                Repository: *<${{ github.repository }}>* 
                Commit: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>
                Author: ${{ github.event.head_commit.author.name }}
                Branch: <https://github.com/${{ github.repository }}/tree/${{ github.ref }}|${{ github.ref }}>
                URL: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}


