name: terraform build and deployment

on: 
  push:
    branches:
      - main
      - set-*
  pull_request:

env:
  AWS_REGION: "us-east-1"
  GITHUB_ROLE_ARN: "arn:aws:iam::342914800082:role/github_oidc_role_expensive-tracker"

# permissions:
#   id-token: write  # This is required for requesting the JWT
#   contents: read   # This is required for actions/checkout

jobs:
    sam-build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
        # - name: configure aws auth
        #   uses: aws-actions/configure-aws-credentials@v4.0.3
        #   with:
        #     role-to-assume: ${{ env.GITHUB_ROLE_ARN }}
        #     role-session-name: GitHub_to_AWS_via_FederatedOIDC
        #     aws-region: ${{ env.AWS_REGION }}
        - name: setup sam
          uses: aws-actions/setup-sam@v2
        - run: |
            ls -R
            cd $GITHUB_WORKSPACE/infra-deploy/sam-app-init
            ls -al
            sam build --use-container
            # echo -e "\033[0;32mDeploying SAM ... \033[0m"
            # sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
      


