name: terraform checks

on: 
  push:
    branches:
      - main
      - feature*
  pull_request:

jobs:
    # terraform-lint:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v4

    #         - name: Set up Terraform
    #           uses: hashicorp/setup-terraform@v3
    #           with:
    #             terraform_version: 1.10.5

    #         - name: Install tflint
    #           run: |
    #             curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

    #         - name: Run tflint
    #           run: |
    #             tflint --version
    #             find . -type f -name "*.tf" | xargs -I {} dirname {} | sort -u | while read DIR; do
    #               echo "Running terraform linter in the : $DIR"
    #               (cd "$DIR" && tflint) || {
    #                 echo "tflint failed in $DIR, please fix the issues"
    #                 exit 1; 
    #               }
    #             done
    # terraform-fmt:
    #         needs: terraform-lint
    #         runs-on: ubuntu-latest
    #         steps:
    #             - name: Checkout repository
    #               uses: actions/checkout@v4

    #             - name: Set up Terraform
    #               uses: hashicorp/setup-terraform@v3
    #               with:
    #                 terraform_version: 1.10.5

    #             - name: Run terraform fmt
    #               run: |
    #                 find . -type f -name "*.tf" | xargs -I {} dirname {} | sort -u | while read DIR; do
    #                   echo "Running terraform fmt in the : $DIR"
    #                   (cd "$DIR" && terraform fmt -check=true) || {
    #                     echo "terraform fmt failed in $DIR, please run terraform fmt to fix the errors"
    #                     exit 1;
    #                   }
    #                 done
    
    # terraform-validate: 
    #     needs: terraform-fmt
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v4

    #         - name: Set up Terraform
    #           uses: hashicorp/setup-terraform@v3
    #           with:
    #             terraform_version: 1.10.5
    #         - name: Install tflint
    #           run: |
    #            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      
    #         - name: Run terraform validate
    #           run: |
    #             find . -type f -name "*.tf" | xargs -I {} dirname {} | sort -u | while read DIR; do
    #               echo "Running terraform validate in the : $DIR"
    #               (cd "$DIR" && terraform init -input=false -backend=false && terraform validate && tflint) || { 
    #                 echo "terraform validate failed in $DIR, please fix the errors"; 
    #                 exit 1; 
    #               }
    #             done
    tfsec:
        # needs: terraform-validate
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: tfsec
              uses: aquasecurity/tfsec-action@v1.0.0
              with:
                additional_args: "--sort-severity	CIRITICAL"
